8330467: NoClassDefFoundError when lambda is in a hidden class
Reviewed-by: psandoz, mchung

# Conflicts:
#	src/java.base/share/classes/java/lang/invoke/InnerClassLambdaMetafactory.java
#	test/jdk/java/lang/invoke/defineHiddenClass/BasicTest.java